#+ summary: Example query calls for 10 triples, will be replaced when dataset is converted to RDF
#+ endpoint: https://api.druid.datalegend.net/datasets/Bramvdhout/Piracy-Database-ANRI/services/test/sparql

SELECT DISTINCT ?s
WHERE {?o <https://iisg.amsterdam/resource/Jaar> ?s}
