#+ summary: Example query calls for 10 triples, will be replaced when dataset is converted to RDF
#+ endpoint: https://api.druid.datalegend.net/datasets/Bramvdhout/Piracy-Database-ANRI/services/test/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?s
WHERE {?o <https://iisg.amsterdam/resource/Jaar> ?s}
