#+ summary: Database containing data retrieved from ANRI-archive detailing mentions of piracy in VOC-empire between 1650-1750.
#+ endpoint: https://api.druid.datalegend.net/datasets/Bramvdhout/Piracy-Database-ANRI/services/test/sparql

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT * WHERE {
  ?Rij <http://data.socialhistory.org/resource/Datum> ?Datum .
  ?Rij <http://data.socialhistory.org/resource/Namen_Zeerovers> ?Zeerovers .
  ?Rij <http://data.socialhistory.org/resource/Gebied> ?Gebied .
}
